# file: jira/tasks/proxy.yml

- name: set JIRA proxy settings
  template: src=connector dest={{jira_installatie_directory}}/{{jira_installatie_versie}}/conf/server.xml group=jira owner=jira force=yes
  when: jira_proxy_name is defined and jira_proxy_port is defined and jira_proxy_scheme is defined

- name: Set JIRA Backdoor Connector in server.xml
  template: src=connector-backdoor dest={{jira_installatie_directory}}/{{jira_installatie_versie}}/conf/server.xml group=jira owner=jira force=yes
  when: jira_backdoor_connector == "yes"

- name: Set JIRA Path in server.xml
  replace: src=connector dest={{jira_installatie_directory}}/{{jira_installatie_versie}}/conf/server.xml regexp='Context path=""' replace='Context path="/{{jira_path}}"' group=jira owner=jira force=yes
  when: jira_path is defined
